[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
sepolia = "${RPC_SEPOLIA}"
base = "${RPC_BASE}"
polygon = "${RPC_POLYGON}"

[etherscan]
sepolia = { key = "${ETHERSCAN_KEY}" }
base = { key = "${BASESCAN_KEY}" }
polygon = { key = "${POLYGONSCAN_KEY}" }